name: Notifications In Slack

on:
  push:
    branches:
      - develop
      - qa
      - main
  schedule:
    - cron: '0 0 * * *'  ## Esto ejecuta la acción una vez al día a la medianoche (UTC)
 
jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,event,action,workflow,ref,URL
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status }}",
                  "title": "${{ github.actor }} pushed new changes",
                  "text": ":tada: Event details:\n- Repository: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- Message: ${{ github.event.head_commit.message }}\n- :globe_with_meridians: Link: https://github.com/${{ github.repository }}"
                }
              ]
            }
